In [35]:
import pandas as pd
#import pandas library

In [36]:
df = pd.read_csv('NYPD_Arrest_Data__Year_to_Date_.csv')
df
#take a look at the data

,ARREST_KEY,ARREST_DATE,PD_CD,PD_DESC,KY_CD,OFNS_DESC,LAW_CODE,LAW_CAT_CD,ARREST_BORO,ARREST_PRECINCT,JURISDICTION_CODE,AGE_GROUP,PERP_SEX,PERP_RACE,X_COORD_CD,Y_COORD_CD,Latitude,Longitude,New Georeferenced Column
0,238013474,12/18/2021,157.0,RAPE 1,104.0,RAPE,PL 1303501,F,Q,105,97,18-24,M,BLACK,1057636,203954,40.726187,-73.735234,POINT (-73.73523390399998 40.72618713000002)
1,236943583,11/25/2021,263.0,"ARSON 2,3,4",114.0,ARSON,PL 1501500,F,K,69,71,25-44,M,BLACK,1014340,171320,40.636868,-73.891586,POINT (-73.89158591899997 40.63686750900007)
2,234938876,10/14/2021,594.0,OBSCENITY 1,116.0,SEX CRIMES,PL 2631100,F,K,61,0,25-44,M,WHITE,995244,155739,40.594145,-73.960415,POINT (-73.96041495199995 40.59414516900005)
3,234788259,10/11/2021,263.0,"ARSON 2,3,4",114.0,ARSON,PL 1501001,F,B,42,71,18-24,M,BLACK,1009058,239616,40.824340,-73.910365,POINT (-73.91036538099996 40.82433953100008)
4,234188790,09/28/2021,578.0,NaN,NaN,NaN,PL 2223001,M,B,44,0,25-44,M,BLACK,1005169,246667,40.843703,-73.924395,POINT (-73.92439508899997 40.84370255600004)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155502,222884924,01/10/2021,397.0,"ROBBERY,OPEN AREA UNCLASSIFIED",105.0,ROBBERY,PL 1601001,F,B,46,0,45-64,M,BLACK,1011432,247605,40.846260,-73.901755,POINT (-73.90175529499999 40.846260031000035)
155503,223918625,02/03/2021,792.0,WEAPONS POSSESSION 1 & 2,118.0,DANGEROUS WEAPONS,PL 2650303,F,K,67,0,18-24,M,BLACK,1004940,180941,40.663302,-73.925425,POINT (-73.92542497899994 40.66330200400005)
155504,224323770,02/13/2021,101.0,ASSAULT 3,344.0,ASSAULT 3 & RELATED OFFENSES,PL 1200001,M,S,121,0,45-64,M,BLACK,942825,166367,40.623227,-74.149227,POINT (-74.14922697299994 40.623226819000074)
155505,222599533,01/04/2021,792.0,WEAPONS POSSESSION 1 & 2,118.0,DANGEROUS WEAPONS,PL 2650303,F,K,73,0,25-44,M,BLACK,1007524,188555,40.684194,-73.916085,POINT (-73.91608474599997 40.684194302000044)
155506,224056881,02/06/2021,268.0,CRIMINAL MIS 2 & 3,121.0,CRIMINAL MISCHIEF & RELATED OF,PL 1451000,F,Q,102,0,18-24,M,ASIAN / PACIFIC ISLANDER,1031414,190787,40.690226,-73.829932,POINT (-73.82993153599993 40.69022556600004)

In [37]:
df.info()
#get some info about the data note: 155507 entries

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 155507 entries, 0 to 155506
Data columns (total 19 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   ARREST_KEY                155507 non-null  int64
 1   ARREST_DATE               155507 non-null  object
 2   PD_CD                     155478 non-null  float64
 3   PD_DESC                   155404 non-null  object
 4   KY_CD                     155404 non-null  float64
 5   OFNS_DESC                 155404 non-null  object
 6   LAW_CODE                  155507 non-null  object
 7   LAW_CAT_CD                154114 non-null  object
 8   ARREST_BORO               155507 non-null  object
 9   ARREST_PRECINCT           155507 non-null  int64
 10  JURISDICTION_CODE         155507 non-null  int64
 11  AGE_GROUP                 155507 non-null  object
 12  PERP_SEX                  155507 non-null  object
 13  PERP_RACE                 155507 non-null  object
 14  X_COORD_CD                155507 non-null  int64
 15  Y_COORD_CD                155507 non-null  int64
 16  Latitude                  155507 non-null  float64
 17  Longitude                 155507 non-null  float64
 18  New Georeferenced Column  155507 non-null  object
dtypes: float64(4), int64(5), object(10)
memory usage: 22.5+ MB

In [38]:
df.isnull().values.any()
#check to see if there are any null values (a field with no values or data)

True

In [39]:
df = df.dropna(how='any',axis=0)
#removing the null values

In [40]:
df.isnull().values.any()

False

In [41]:
df.info()
#there are less entries now than previous because of the removal of the null

<class 'pandas.core.frame.DataFrame'>
Index: 154011 entries, 0 to 155506
Data columns (total 19 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   ARREST_KEY                154011 non-null  int64
 1   ARREST_DATE               154011 non-null  object
 2   PD_CD                     154011 non-null  float64
 3   PD_DESC                   154011 non-null  object
 4   KY_CD                     154011 non-null  float64
 5   OFNS_DESC                 154011 non-null  object
 6   LAW_CODE                  154011 non-null  object
 7   LAW_CAT_CD                154011 non-null  object
 8   ARREST_BORO               154011 non-null  object
 9   ARREST_PRECINCT           154011 non-null  int64
 10  JURISDICTION_CODE         154011 non-null  int64
 11  AGE_GROUP                 154011 non-null  object
 12  PERP_SEX                  154011 non-null  object
 13  PERP_RACE                 154011 non-null  object
 14  X_COORD_CD                154011 non-null  int64
 15  Y_COORD_CD                154011 non-null  int64
 16  Latitude                  154011 non-null  float64
 17  Longitude                 154011 non-null  float64
 18  New Georeferenced Column  154011 non-null  object
dtypes: float64(4), int64(5), object(10)
memory usage: 23.5+ MB

In [42]:
df.isna().sum()
#check to see if there are any NaN (not a number)

ARREST_KEY                  0
ARREST_DATE                 0
PD_CD                       0
PD_DESC                     0
KY_CD                       0
OFNS_DESC                   0
LAW_CODE                    0
LAW_CAT_CD                  0
ARREST_BORO                 0
ARREST_PRECINCT             0
JURISDICTION_CODE           0
AGE_GROUP                   0
PERP_SEX                    0
PERP_RACE                   0
X_COORD_CD                  0
Y_COORD_CD                  0
Latitude                    0
Longitude                   0
New Georeferenced Column    0
dtype: int64

In [43]:
df.columns

Index(['ARREST_KEY', 'ARREST_DATE', 'PD_CD', 'PD_DESC', 'KY_CD', 'OFNS_DESC',
       'LAW_CODE', 'LAW_CAT_CD', 'ARREST_BORO', 'ARREST_PRECINCT',
       'JURISDICTION_CODE', 'AGE_GROUP', 'PERP_SEX', 'PERP_RACE', 'X_COORD_CD',
       'Y_COORD_CD', 'Latitude', 'Longitude', 'New Georeferenced Column'],
      dtype='object')

In [44]:
#df_arrest = df.drop(["ARREST_KEY","PD_CD","KY_CD","LAW_CODE","LAW_CAT_CD","JURISDICTION_CODE","X_COORD_CD","Y_COORD_CD"], axis=1)
#remove unwanted columns

In [46]:
df = df.copy()
df.rename({
    'ARREST_DATE': 'Arrest Date',
    'PD_DESC': 'Police Description',
    'OFNS_DESC': 'Offense Description',
    'LAW_CAT_CD': 'Level of offense',
    'ARREST_PRECINCT': 'Arrest Precinct',
    'ARREST_BORO': 'Arrest Borough',
    'AGE_GROUP': 'Age Group',
    "PERP_SEX": "Perpetrator's Sex",
    "PERP_RACE": "Perpetrator's Race",
    'JURISDICTION_CODE': 'Jurisdiction Code',
    'LAW_CODE': 'Law Code',
    'X_COORD_CD': 'X Coordinate',
    'Y_COORD_CD': 'Y Coordinate',
    'ARREST_KEY': 'Arrest Key'
}, axis=1, inplace=True)

In [47]:
df.to_csv('NYPD_Arrest_nullremoved1.csv')

In [48]:
df

,Arrest Key,Arrest Date,PD_CD,Police Description,KY_CD,Offense Description,Law Code,Level of offense,Arrest Borough,Arrest Precinct,Jurisdiction Code,Age Group,Perpetrator's Sex,Perpetrator's Race,X Coordinate,Y Coordinate,Latitude,Longitude,New Georeferenced Column
0,238013474,12/18/2021,157.0,RAPE 1,104.0,RAPE,PL 1303501,F,Q,105,97,18-24,M,BLACK,1057636,203954,40.726187,-73.735234,POINT (-73.73523390399998 40.72618713000002)
1,236943583,11/25/2021,263.0,"ARSON 2,3,4",114.0,ARSON,PL 1501500,F,K,69,71,25-44,M,BLACK,1014340,171320,40.636868,-73.891586,POINT (-73.89158591899997 40.63686750900007)
2,234938876,10/14/2021,594.0,OBSCENITY 1,116.0,SEX CRIMES,PL 2631100,F,K,61,0,25-44,M,WHITE,995244,155739,40.594145,-73.960415,POINT (-73.96041495199995 40.59414516900005)
3,234788259,10/11/2021,263.0,"ARSON 2,3,4",114.0,ARSON,PL 1501001,F,B,42,71,18-24,M,BLACK,1009058,239616,40.824340,-73.910365,POINT (-73.91036538099996 40.82433953100008)
5,234117071,09/27/2021,157.0,RAPE 1,104.0,RAPE,PL 1303501,F,K,84,0,25-44,M,BLACK,989013,192652,40.695469,-73.982825,POINT (-73.98282507899995 40.69546894100006)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155502,222884924,01/10/2021,397.0,"ROBBERY,OPEN AREA UNCLASSIFIED",105.0,ROBBERY,PL 1601001,F,B,46,0,45-64,M,BLACK,1011432,247605,40.846260,-73.901755,POINT (-73.90175529499999 40.846260031000035)
155503,223918625,02/03/2021,792.0,WEAPONS POSSESSION 1 & 2,118.0,DANGEROUS WEAPONS,PL 2650303,F,K,67,0,18-24,M,BLACK,1004940,180941,40.663302,-73.925425,POINT (-73.92542497899994 40.66330200400005)
155504,224323770,02/13/2021,101.0,ASSAULT 3,344.0,ASSAULT 3 & RELATED OFFENSES,PL 1200001,M,S,121,0,45-64,M,BLACK,942825,166367,40.623227,-74.149227,POINT (-74.14922697299994 40.623226819000074)
155505,222599533,01/04/2021,792.0,WEAPONS POSSESSION 1 & 2,118.0,DANGEROUS WEAPONS,PL 2650303,F,K,73,0,25-44,M,BLACK,1007524,188555,40.684194,-73.916085,POINT (-73.91608474599997 40.684194302000044)
155506,224056881,02/06/2021,268.0,CRIMINAL MIS 2 & 3,121.0,CRIMINAL MISCHIEF & RELATED OF,PL 1451000,F,Q,102,0,18-24,M,ASIAN / PACIFIC ISLANDER,1031414,190787,40.690226,-73.829932,POINT (-73.82993153599993 40.69022556600004)